In [5]:
import numpy as np


In [7]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
Dimensions array

In [13]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


In [ ]:
1 d array

In [14]:
arr = np.array()
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [ ]:
2 d array

In [17]:
arr = np.array([[1,2,3],[5,6,7]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [5 6 7]]
2


In [ ]:
3 d array

In [21]:
arr = np.array([[[1,2,3],[5,6,7]],[[3,2,1],[8,9,0]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [5 6 7]]

 [[3 2 1]
  [8 9 0]]]
3


In [22]:
arr = np.array([1,2,3,4], ndmin=5))

print(arr)
print('Number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


In [23]:
#indexing
arr = np.array([2,3,4,5])
print(arr[0])

2


In [ ]:
Part 2

In [ ]:
Slicing numpy arrays

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [4]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [ ]:
Slicing in 2D array

In [9]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[1,1:4])

[70 80 90]


In [11]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[0,0:3])

[10 20 30]


In [ ]:
Checking Data types of an  array

In [12]:
arr = np.array([1,2,3,4,5,6,7])
print(arr.dtype)

int64


In [13]:
arr = np.array(['animals','bat','cat'])
print(arr.dtype)

<U7


In [ ]:
Creating arrays withe defined data type

In [14]:
arr = np.array([1,2,3,4,5,6,7], dtype ='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']
|S1


In [ ]:
Create an array with data types 4 bytes integer

In [15]:
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
Numpy array Shape

#The shape of an array is the number of elemnts in each dimension

In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [18]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
print(arr.shape)

(1, 3, 4)


In [ ]:
Joining Numpy Arrays

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
Join 2D arrays

In [4]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis = 0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
Splitting numpy arrays

In [ ]:
Spliting array in 3 parts

In [6]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
Spliting array in 4 parts

In [7]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


#Ravel and flatten

In [ ]:
Converts multidimensional array into 1d array

In [9]:
m= np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimension is ", m.ndim)
n = m.ravel()
print(n)
print("Now the new dimenion is ", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
Now the new dimenion is  1


In [1]:
import numpy as np


In [2]:
m= np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimension is ", m.ndim)
n = m.flatten()
print(n)
print("Now the new dimenion is ", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
Now the new dimenion is  1


In [5]:
c = np.array([[[[1,2,3],[78,89,25],[45,26,84]]]])
print(c)
print("The dimension is", c.ndim)
d = c.ravel()
print(d)
print("Now the new dimension is ", d.ndim)

[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]
The dimension is 4
[ 1  2  3 78 89 25 45 26 84]
Now the new dimension is  1


#Unique Function

In [8]:
k = np.array([1,2,3,4,5,6,7,8,54,23,32,7,4])
print(k)
x = np.unique(k)
print(x)

[ 1  2  3  4  5  6  7  8 54 23 32  7  4]
[ 1  2  3  4  5  6  7  8 23 32 54]


In [9]:
k = np.array([1,2,3,4,5,6,7,8,54,23,32,7,4])
print(k)
x = np.unique(k, return_index = True)
print(x)

[ 1  2  3  4  5  6  7  8 54 23 32  7  4]
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 23, 32, 54]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10,  8]))


In [12]:
k = np.array([1,2,3,4,5,6,7,8,54,23,32,7,4])
print(k)
x = np.unique(k, return_index = True, return_counts = True)
print(x)

[ 1  2  3  4  5  6  7  8 54 23 32  7  4]
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 23, 32, 54]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10,  8]), array([1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1]))


In [14]:
a = np.array([1,2,3,4,5])
d = np.delete(a, [2])
print(d)

[1 2 4 5]


In [16]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,3,6,3]])
print(a)
b = np.delete(a, 1, axis = 0)
print()
print(b)

[[1 2 3 4]
 [5 6 7 8]
 [9 3 6 3]]

[[1 2 3 4]
 [9 3 6 3]]
